### ISSUE TITLE
This will always be true as the response is a List and ID is definitely not expected here. Hence when do getAllConnections, the response is available only on Catch block.

### ISSUE THREAD

**Issue by vabtrix** [basiqio/basiq-sdk-nodejs#2]
https://github.com/basiqio/basiq-sdk-nodejs/blob/a2039afbc179db22dd9d9881186fe3fd599f35dc/src/services/User.js#L112

**Comment by vabtrix** [comment]
Also, The documentation says, 
To Get All Connections for a User, Pass the UserId, but whats required is in fact, just a user Object. 
`this.getAllConnections = function (user <object>, filter) {
        return new Promise(function (res, rej) {
            let url = "users/" + user.id + "/connections"; 
         }
}`

**Comment by nenadlukic** [comment]
Fixed
