### ISSUE TITLE
New User creation needs both Email and Mobile, failing either one, does not create a user.  

### ISSUE THREAD

**Issue by vabtrix** [basiqio/basiq-sdk-nodejs#3]
But either one of them should allow you to create a New User as per the documentation.

https://github.com/basiqio/basiq-sdk-nodejs/blob/a2039afbc179db22dd9d9881186fe3fd599f35dc/src/services/User.js#L64
The above statement requires email and mobile. Which makes both of them mandatory for a new user to be created. !!

it should be really 
```
if (!data || !(data.email || data.mobile)) {
   // Cannot create a user if either one of them 
   // also return if no data provided. 
}else{
  //create a new user
}
```

**Comment by nenadlukic** [comment]
Thank you for noticing this, I will fix it immediately.

**Comment by nenadlukic** [comment]
Fixed in v.1.0.4
