### ISSUE TITLE
delete call returns empty response - fails in json parse

### ISSUE THREAD

**Issue by raghu-bluepineapple** [basiqio/basiq-sdk-nodejs#6]
when delete returns an empty response in API.js  (line 44)
```javascript
            try {
                res(JSON.parse(body));
            } catch (err) {
                res(null);
            }
```

API.send, res(body) fails with Uncaught SyntaxError: Unexpected end of JSON input  - should probably check for empty
```javascript
res(body ? JSON.parse(body) : {})
```
or similar.

**Comment by aterentic-basiq** [comment]
Hello @raghu-bluepineapple , thanks for noticing, we have changed code to:

`            try {
                res(!!body ? JSON.parse(body) : {});
            } catch (err) {
                rej(err);
            }
`
as it should return error in case of failed parsing. Just in case we missed something, did you got any error, or it is just advice, as we didn't manage to reproduce error (it fallbacks to res(null) case)?

**Comment by raghu-bluepineapple** [comment]
Hi, 
thanks for the fix - the basiq service was returning a success response but no body at all in case of DELETE user. hence the fail.
